# This docker-compose file can be used during local development to spin up
# the Postgres and Redis servers you need.
#
# It does NOT run the app server for you.
version: "3"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data
    ports:
      - 6379:6379
volumes:
  postgres:
    external: false
  redis:
    external: false
